name: textomize
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  # external dependencies 
  cupertino_icons: ^1.0.8
  svg_flutter: ^0.0.1
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  smooth_page_indicator: ^1.2.0+3
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  pdfx: ^2.8.0
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.1
  curved_navigation_bar: ^1.0.6
  file_picker: ^9.0.0
  
  image_cropper: 9.0.0
  google_mlkit_text_recognition: ^0.13.0
  translator: ^1.0.3+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/png/
    - assets/png/LogoWhite.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
